FROM mcr.microsoft.com/devcontainers/python:3.13

ENV \
  DEBIAN_FRONTEND=noninteractive \
  DEVCONTAINER=true \
  PATH=$PATH:./node_modules/.bin \
  SUPERVISOR_HOST=192.168.0.11:8123 \
  SUPERVISOR_TOKEN=ca083b73a2eaf35f7de25440013ad6829ae274bacc2278bd3cae2d95f6d4a9f79d5a74b046a4165889c36fee80d32fd41d8c62dee26e04b4 \
  FRONTEND_PATH=/workspaces/frontend
