FROM mcr.microsoft.com/devcontainers/python:3.13

ENV \
  DEBIAN_FRONTEND=noninteractive \
  DEVCONTAINER=true \
  PATH=$PATH:./node_modules/.bin \
  SUPERVISOR_HOST=192.168.0.11:8123 \
  FRONTEND_PATH=/workspaces/home_assistant-frontend
